services:
  - type: web
    name: orgulho-da-cidade
    runtime: node
    buildCommand: npm ci --omit=dev
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NODE_MODULES_CACHE
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: PostgreSQL
          property: connectionString
    healthCheckPath: /
    maxInstances: 1

