services:
  - type: web
    name: orgulho-da-cidade
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000    disk:
      - path: /opt/render/project/data
        name: sqlite-db
        sizeGB: 1